/* eslint-disable @next/next/no-page-custom-font */
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Employee from "../components/Employee";
import EmployeesProps from "../types/employees.types";

const Home: NextPage<EmployeesProps> = ({ employees }) => {
  return (
    <>
      <Head>
        <title>Employees</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Open+Sans:ital@1&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <h1 className={styles.titleText}>Active employees</h1>
      <main className={styles.main}>
        <div className={styles.container}>
          {employees.map(({ id, address, email, name }) => (
            <div key={id}>
              <Employee id={id} name={name} address={address} email={email} />
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const resEmployees = await fetch(
    "https://jsonplaceholder.typicode.com/users"
  );
  const employees = await resEmployees.json();

  return {
    props: {
      employees,
    },
  };
};
